name             'cookbooks/plugins_deploy'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks/plugins_deploy'
long_description 'Installs/Configures cookbooks/plugins_deploy'
version          '0.1.0'
